import timer from "./modules/timer";
import menu from "./modules/menu";
import modal from "./modules/modal";
import valid from "./modules/valid";
import tabs from "./modules/tabs";
import slider from "./modules/slider";
import addDots from "./modules/addDots";
timer("24 february 2022");
menu();
addDots();
modal();
valid();
tabs();
slider();
