import timer from "./modules/timer";
import menu from "./modules/menu";
import modal from "./modules/modal";
import valid from "./modules/valid";
import tabs from "./modules/tabs";
import calc from "./modules/calc";
timer("24 february 2022");
menu();
modal();
valid();
tabs();
calc(100);
